# EXERCICIS OPERACIONS AMB NUMPY

In [367]:
import numpy as np
np.__version__  

'1.24.1'

## 1- Genera un array que contingui 25 elements entre 0 i 99 seguint una distribució lineal.

In [368]:
array = np.linspace(0, 99, 25)

### Després, transforma aquest matriu en una matriu de 5 x 5.

In [369]:
array = array.reshape(5, 5)
print(array)

[[ 0.     4.125  8.25  12.375 16.5  ]
 [20.625 24.75  28.875 33.    37.125]
 [41.25  45.375 49.5   53.625 57.75 ]
 [61.875 66.    70.125 74.25  78.375]
 [82.5   86.625 90.75  94.875 99.   ]]


### Quina és la diagonal de la matriu?

In [370]:
print(array.diagonal())

[ 0.   24.75 49.5  74.25 99.  ]


### I la diagonal just superior?

In [371]:
print(array.diagonal(offset=1))

[ 4.125 28.875 53.625 78.375]


## 2- Crea un array de 5 x 4 amb el valor repetit 5.

In [372]:
other = np.full((4,5),5)

### Uneix aquesta matriu a la matriu de l'exercici anterior per aconseguir dues noves matrius, una de 5 x 9

In [373]:
print(np.concatenate((array,other),axis=0))

[[ 0.     4.125  8.25  12.375 16.5  ]
 [20.625 24.75  28.875 33.    37.125]
 [41.25  45.375 49.5   53.625 57.75 ]
 [61.875 66.    70.125 74.25  78.375]
 [82.5   86.625 90.75  94.875 99.   ]
 [ 5.     5.     5.     5.     5.   ]
 [ 5.     5.     5.     5.     5.   ]
 [ 5.     5.     5.     5.     5.   ]
 [ 5.     5.     5.     5.     5.   ]]


### i una altra de 9 x 5.

In [374]:
other = np.full((5,4),5)

In [375]:
print(np.concatenate((array,other),axis=1))

[[ 0.     4.125  8.25  12.375 16.5    5.     5.     5.     5.   ]
 [20.625 24.75  28.875 33.    37.125  5.     5.     5.     5.   ]
 [41.25  45.375 49.5   53.625 57.75   5.     5.     5.     5.   ]
 [61.875 66.    70.125 74.25  78.375  5.     5.     5.     5.   ]
 [82.5   86.625 90.75  94.875 99.     5.     5.     5.     5.   ]]


## 3- Tenint l'array inicial que podeu veure emmarcat, heu de realitzar les operacions necessàries per obtenir l'array: array(['Aquesta', 'Classe', 'De', 'DAM', 'Intel·ligents'], dtype='<U12')

In [376]:
initial = np.array(['     aquesta classe és de dam intel·ligents    '])

In [377]:
initial = np.char.capitalize(np.array([x.strip() for x in initial[0].split()]))
print(initial)

['Aquesta' 'Classe' 'És' 'De' 'Dam' 'Intel·ligents']


### Quins elements de l'array comencen per 'D'?

In [378]:
initial = np.char.startswith(initial, 'D')
print(initial)

[False False False  True  True False]


## 4- Donades dues matrius A i B
        [ 3 1 2 ]   
    A = [ 4 1 3 ] 
        [ 2 0 1 ] 

        [ 2 0 3 ]   
    B = [ 1 1 1 ] 
        [ 0 2 4 ] 

In [379]:
A = np.array([[3, 1, 2], [4, 1, 3], [2, 0, 1]])
B = np.array([[2, 0, 3], [1, 1, 1], [0, 2, 4]])

### Realitza la multiplicació matricial de AxB i BxA. Són iguals? 

In [380]:
print(A.dot(B))
print(B.dot(A))
print(A.dot(A) == B.dot(B))

[[ 7  5 18]
 [ 9  7 25]
 [ 4  2 10]]
[[12  2  7]
 [ 9  2  6]
 [16  2 10]]
[[False False False]
 [False False False]
 [False False False]]


### Realitza la multiplicació de la matriu A x 2

In [381]:
print(A*2)

[[6 2 4]
 [8 2 6]
 [4 0 2]]


### Quan és la multiplicació escalar d'AxB? i de BxA? Són iguals?

In [382]:
print(np.sum(A*B))
print(np.sum(B*A))
print(np.sum(A*B) == np.sum(B*A))

24
24
True


## 5- Usant la matriu A de l'exercici anterior, calcula:

### A^3

In [383]:
print(A.dot(A.dot(A)))

[[ 89  21  57]
 [114  27  73]
 [ 42  10  27]]


### El determinant d'A

In [384]:
print(np.linalg.det(A))

1.0


### Resol l'equació Ax = y, essent *y* l'array [3,2,5]

In [385]:
y = np.array([3, 2, 5])
print(np.linalg.solve(A, y))

[ 6. -1. -7.]
